server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php;

    # Обработка статических файлов
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Проксирование PHP-запросов на PHP-FPM через TCP
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Запрет доступа к скрытым файлам
    location ~ /\. {
        deny all;
    }
}
